### ISSUE TITLE
Spam Answer is always incorrect

### ISSUE THREAD

**Issue by jules27** [matthutchinson/acts_as_textcaptcha#11]
I'm trying to use this gem to stop spam comments, but for some reason I'm always getting "Spam answer is incorrect, try another question instead" when I try to make a new comment, either via the form or on the Rails console.

I've added the gem in my Gemfile.

Controller:

``` ruby
@comment = Comment.new
@comment.textcaptcha
```

Model:

``` ruby
class Comment < ActiveRecord::Base
  attr_accessible :text, :name

  validates_presence_of :text, :name

  acts_as_textcaptcha bcrypt_salt: Settings.text_captcha_salt,
                      questions: [{ 'question' => '1+1', 'answers' => '2,two' }]
end
```

Form view:

``` haml
= simple_form_for @comment do |f|
  = f.input :name
  = f.input :text, as: :text

  = f.label :spam_answer, comment.spam_question
  = f.text_field :spam_answer, value: ''
  %br

  = f.submit "Post Comment"
```

acts_as_textcaptcha config file:

``` yaml
development: &common_settings
  bcrypt_salt: <salt omitted>
  bcrypt_cost: 10
  questions:
      - question: 'Is ice hot or cold?'
        answers: 'cold'
      - question: 'what color is an orange?'
        answers: 'orange'
      <rest of the questions omitted>

test:
  <<: *common_settings
  bcrypt_salt: <salt omitted>
  bcrypt_cost: 1

production:
  <<: *common_settings
```

Adding comment through Rails console:

``` terminal
> a = Comment.new("name"=>"Hi", "text"=>"asdf", "spam_answer"=>"2")
> a.valid?
 => false 
> a.errors.messages
 => {:spam_answer=>["is incorrect, try another question instead"]} 
```

Can you see if I'm missing something obvious? Thanks!
